# Site settings
title: Good Hope Baptist Church
email: tgray.it@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the ministry of Good Hope Baptist Church! We have a deep desire to care for all people, and grow together in our knowledge of Christ.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://goodhopebaptist.org/" # the base hostname & protocol for your site
twitter_username: jtgry
github_username:  jtgry

# Build settings
markdown: kramdown

collections:
    ministries:
      output: true

sunday:
  - category: Sunday School
    time: 9:15 a.m.
  - category: Sunday Worship
    time: 10:30 a.m.
  - category: Discipleship Training
    time: 5:00 p.m.
  - category: Sunday Night Worship
    time: 6:00 p.m.

wednesday:
  - category: Evening Worship
    time: 6:00 p.m
